---
# vars file for packages

# Prereq packages: they get installed first, so put things like epel-release here
_packages_prereq:
  all:
    - sudo
    - bash
    - tar
    - unzip
    - bzip2
  CentOS:
    - epel-release
  Fedora:
    - fedora-workstation-repositories

# Base packages
_packages_base:
  all:
    - bash-completion
    - zsh
    - ed
    - vim
    - mc
    - aspell-en
    - tmux
    - bc
    - less
  CentOS:
    - which
    - xz
    - tuned
    - lvm2
    - vdo
    - kmod-kvdo
  RedHat:
    - xz
    - tuned
    - lvm2
    - vdo
    - kmod-kvdo
    - stratisd
    - stratis-cli
  Fedora:
    - xz
    - tuned
    - lvm2
    - vdo
    - kmod-kvdo
    - stratisd
    - stratis-cli
  Debian:
    - xz-utils
    - apt-file
    - debianutils
    - command-not-found
  Ubuntu:
    - xz-utils
    - apt-file
    - debianutils
    - command-not-found

# Packages tools
_packages_tools:
  all:
    - lsof
    - sysstat
    - htop
    - strace
    - iotop

# Net tools packages
_packages_net:
  all:
    - curl
    - wget
    - traceroute
    - net-tools
    - tcpdump
  CentOS:
    - bind-utils
    - nmap-ncat
  RedHat:
    - bind-utils
    - nmap-ncat
  Fedora:
    - bind-utils
    - nmap-ncat
  Debian:
    - dnsutils
    - ncat
  Ubuntu:
    - dnsutils
    - ncat


# Build packages
_packages_build:
  all:
    - git
  CentOS:
    - openssl-devel
    - elfutils-libelf-devel
    - ncurses-libs
    - ncurses-devel
    - flex
    - bison
    - bc
    - kernel-headers
    - kernel-devel
    - gcc
    - binutils
    - perl
    - make
    - dialog
    - kexec-tools
  RedHat:
    - openssl-devel
    - elfutils-libelf-devel
    - ncurses-libs
    - ncurses-devel
    - flex
    - bison
    - bc
    - kernel-headers
    - kernel-devel
    - gcc
    - binutils
    - perl
    - make
    - dialog
    - kexec-tools
  Fedora:
    - openssl-devel
    - elfutils-libelf-devel
    - ncurses-libs
    - ncurses-devel
    - flex
    - bison
    - bc
    - kernel-headers
    - kernel-devel
    - gcc
    - binutils
    - perl
    - make
    - dialog
    - kexec-tools
  Debian:
    - build-essential
  Ubuntu:
    - build-essential

# Clients packages
_packages_clients:
  all:
    - rsync
    - cifs-utils
    - samba-client
    - openldap-clients
    - nfs-utils
    - openssh-clients
  CentOS:
    - openldap-clients
  RedHat:
    - openldap-clients
  Fedora:
    - openldap-clients
  Debian:
    - ldap-utils
  Ubuntu:
    - ldap-utils

# Devel packages
_packages_devel:
  all:
    - npm
    - nodejs
    - cargo
    - ruby
    - cloc
  CentOS:
    - java-11-openjdk
    - rust
    - go
    - rpm-build
    - rpmdevtools
  RedHat:
    - java-11-openjdk
    - rust
    - go
    - rpm-build
    - rpmdevtools
  Fedora:
    - java-11-openjdk
    - rust
    - go
    - rpm-build
    - rpmdevtools
  Debian:
    - openjdk-11-jdk
    - rustc
    - golang
  Ubuntu:
    - openjdk-11-jdk
    - rustc
    - golang

# GUI packages
_packages_gui:
  all:
    - wireshark
  CentOS:
    - "@^graphical-server-environment"
    - firewall-config
    - "system-config-*"
  RedHat:
    - "@^graphical-server-environment"
    - firewall-config
  Fedora:
    - "@^gnome-desktop-environment"
    - firewall-config
    - firefox
    - kepassx2
    - remmina
    - mediawriter
  Debian:
    - task-gnome-desktop
    - firefox-esr
  Ubuntu:
    - unity
    - firefox-esr

# Desktop packages (specific to desktop environments)
_packages_desktop:
  all:
    - figlet
  Fedora:
    - lm_sensors
    - wine-fonts
    - powerline-fonts
    - flameshot
    - transmission

packages_prereq: "{{ _packages_prereq['all'] + ( _packages_prereq[ansible_distribution] | default([]) ) }}"
packages_base: "{{ _packages_base['all'] + ( _packages_base[ansible_distribution] | default([]) ) }}"
packages_net: "{{ _packages_net['all'] + ( _packages_net[ansible_distribution] | default([]) ) }}"
packages_tools: "{{ _packages_tools['all'] + ( _packages_tools[ansible_distribution] | default([]) ) }}"
packages_build: "{{ _packages_build['all'] + ( _packages_build[ansible_distribution] | default([]) ) }}"
packages_clients: "{{ _packages_clients['all'] + ( _packages_clients[ansible_distribution] | default([]) ) }}"
packages_devel: "{{ _packages_devel['all'] + ( _packages_devel[ansible_distribution] | default([]) ) }}"
packages_gui: "{{ _packages_gui['all'] + ( _packages_gui[ansible_distribution] | default([]) ) }}"
packages_desktop: "{{ _packages_desktop['all'] + ( _packages_desktop[ansible_distribution] | default([]) ) }}"
