namespace: "crivetimihai"
name: "workstation"
version: "1.0.10"
readme: "README.md"
authors:
  - "Mihai Criveti (https://twitter.com/crivetimihai)"
description: "Collection of Workstation Tools"
license:
  - "MIT"
tags:
  - linux
  - workstation
  - baseline
  - profile
  - dotfiles
  - micro
  - pip
  - anaconda
  - collection
repository: "https://www.github.com/crivetimihai/ansible_workstation"
homepage: "https://www.github.com/crivetimihai/ansible_workstation"
documentation: "https://www.github.com/crivetimihai/ansible_workstation"
issues: "https://www.github.com/crivetimihai/ansible_workstation/issues"
