---
# ansible-playbook -i localhost, playbook.yml

- hosts: all
  connection: local
  gather_facts: yes
  roles:
    - role: baseline
    - role: packages
    - role: micro
    - role: pandoc
    - role: profile
    - role: dotfiles
    - role: flatpak
    - role: pip
    - role: npm
    - role: secure

