---
# ansible-playbook -i localhost, playbook.yml

- hosts: all
  connection: local
  gather_facts: yes
  roles:
    - role: dotfiles
    - role: profile
    - role: packages
    - role: baseline
    - role: micro
