---
# tasks file for dotfiles

- name: install git
  package:
    name: git
    state: present
  become: yes

- name: download spacevim installer
  get_url:
    url: https://spacevim.org/install.sh
    dest: /tmp/install-spacevim.sh
    mode: '0777'

- name: install spacevim
  command: bash /tmp/install-spacevim.sh

- name: checkout spacemacs
  git:
    version: "HEAD"
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d

- name: checkout dotfiles git repo
  git:
    version: "{{ dotfiles_repo_version }}"
    repo: "{{ dotfiles_repo }}"
    dest: ~/dotfiles
    update: yes
  become: no

- name: link dotfiles
  file:
    src: "~/dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  become: no
  with_items: "{{ dotfiles_files }}"
