---
# Install various cloud CLIs and tools

- name: assert supported distributions and versions
  assert:
    that:
      - ( ansible_distribution == "RedHat" and ( ansible_distribution_major_version == '8' )
        ) or
        ( ansible_distribution == "CentOS" and ( ansible_distribution_major_version == "7" )
        ) or
        ( ansible_distribution == "Fedora" and ( ansible_distribution_major_version == "30" )
        )

- include: docker-compose.yml
- include: kompose.yml
- include: kubectl.yml
- include: helm.yml
- include: aws.yml
- include: ibmcloud.yml
- include: azure.yml